# SQLite (dev / test)
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

# ===== Production: PostgreSQL on Render =====
production:
  primary:
    # Render の PostgreSQL の接続URLを使う（例: postgres://...）
    url: <%= ENV.fetch("DATABASE_URL") %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

  # solid_cache / solid_queue / solid_cable も同じDBを使わせる
  # （必要なら別DB用の環境変数を後で用意）
  cache:
    url: <%= ENV.fetch("SOLID_CACHE_DATABASE_URL", ENV["DATABASE_URL"]) %>
    migrations_paths: db/cache_migrate

  queue:
    url: <%= ENV.fetch("SOLID_QUEUE_DATABASE_URL", ENV["DATABASE_URL"]) %>
    migrations_paths: db/queue_migrate

  cable:
    url: <%= ENV.fetch("SOLID_CABLE_DATABASE_URL", ENV["DATABASE_URL"]) %>
    migrations_paths: db/cable_migrate